version: 2

submodules:
  include: all

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
  apt_packages:
  - cmake
  jobs:
    post_install:
    - pip install pdoc
    - pdoc -o tmp client/blindai/client.py
    - mv tmp/blindai/client.html docs/resources/api.html

mkdocs:
  configuration: mkdocs.yml

python:
    install:
    - requirements: docs/requirements.txt
    - requirements: client/requirements.txt
    - method: pip
      path: client
